### ISSUE TITLE
Printed version some comments

### ISSUE THREAD

**Issue by jecisc** [SquareBracketAssociates/EnterprisePharo#102]
I saw two things that can be improved so far:

1) 

https://github.com/SquareBracketAssociates/EnterprisePharo/blob/master/PillarChap/Pillar.pillar#L533
https://github.com/SquareBracketAssociates/EnterprisePharo/blob/master/PillarChap/Pillar.pillar#L539

Maybe "My working script" is a better English. If you agree I can do a PR to correct it.

2) This seems to be a Pillar or sbabook issue. Scripts with captions appears in the Illustration table. For example page viii there is a reference to a script page 220.

@DamienCassou

**Comment by cdlm** [comment]
For 2) it's a feature. That script has a label, meaning it's referenced somewhere, so it has to appear in the table of illustrations (which centralizes all labeled floats with no distinction of type)

**Comment by jecisc** [comment]
Don't you think it should be renamed "Illustrations and scripts" if it's a feature?

**Comment by cdlm** [comment]
Sure, why not "Illustrations, figures, tables, and scripts (and whatever)" :trollface:

**Comment by DamienCassou** [comment]
Thanks Cyril. I agree with Damien that 2) is fine.
