### ISSUE TITLE
HTML not generated anymore

### ISSUE THREAD

**Issue by jecisc** [SquareBracketAssociates/EnterprisePharo#109]
Since Pillar 4 the html is not generated anymore. 
This broke books.pharo.org.

See: https://ci.inria.fr/pharo-contribution/view/Books/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/PillarChap/

/cc @YannDub @ThibaultAr

**Comment by YannDub** [comment]
We have a problem with headerLevelOffset, in HTML, we compile all chapters and the PRHeadingLevelOffsetTransformer crash because we have not a title of level 2.

**Comment by jecisc** [comment]
If this is a Pillar issue could you open an issue on Pillar's forge?

**Comment by YannDub** [comment]
HTML is now generated

See : https://ci.inria.fr/pharo-contribution/view/Books/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/PillarChap/
