### ISSUE TITLE
Remove main Pillar file and create a main latex file

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#22]
The `EnterprisePharo.pillar` is basically a LaTeX file with Pillar syntax. It would be better to write it in LaTeX directly. Moreover, now that chapter titles are metadata, the approach does not work anymore because the resulting book gets no chapter title at all.

**Comment by cdlm** [comment]
seems to be done

**Comment by cdlm** [comment]
oops, no, there needs to be a main HTML file as well, and `EnterprisePharo.pillar` is still there ATM

**Comment by DamienCassou** [comment]
The HTML file comes from the website.
