### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by cdlm** [SquareBracketAssociates/EnterprisePharo#23]
Most certainly a Pillar issue, but links are currently shown unformatted (like markup, just missing the first star) in the PDF (branch sbabook)

**Comment by DamienCassou** [comment]
Name: Pillar-PetitPillar-DamienCassou.125
Author: DamienCassou
Time: 5 October 2015, 10:22:05.660946 am
UUID: 8c4c4783-5e6d-4735-a6cd-5e5c23ca405e
Ancestors: Pillar-PetitPillar-DamienCassou.124

Fix linkAlias definition
