### ISSUE TITLE
Missing backcover

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#29]
We need some content for the back of the book. Luc proposed to copy/paste the "About the book" page, changing the title to "Enterprise Pharo..."

**Comment by DamienCassou** [comment]
Damien P. recommends:

- font opensans
- contributors in columns, just like inside the book
- chapter titles and maybe part titles (maybe starting with "This book is organized in these chapters")

**Comment by DamienCassou** [comment]
- esug logo ?
- license CC logo ?
- Pharo logo ?

**Comment by DamienCassou** [comment]
what do you think about it guys? Should we add a logo (see above?).

![cover](https://cloud.githubusercontent.com/assets/217543/14433297/1009729c-000e-11e6-972c-63ec7af622f3.png)

**Comment by jecisc** [comment]
IMO yes :)

**Comment by svenvc** [comment]
Nice. Yes, some small logo or some color in the style of the front cover would be good.

**Comment by DamienCassou** [comment]
Sven Van Caekenberghe <notifications@github.com> writes:

> Nice. Yes, some small logo or some color in the style of the front cover would be good.

which logo do you expect? Lusy, who did the cover, will work on the
backcover (maybe adding back the orange blocks of the cover).

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jfabry** [comment]
I think the backcover looks good as is, straight to the point. Putting logos there will clutter the space that now is very clear. So I would not do that.

**Comment by DamienCassou** [comment]
Here it is:

![cover](https://cloud.githubusercontent.com/assets/217543/14747887/258d460a-08b7-11e6-9bf0-a63fd9d3d795.png)

**Comment by LucFabresse** [comment]
Nice
Thanks Damien!


#Luc

2016-04-22 18:22 GMT+02:00 Damien Cassou <notifications@github.com>:

**Comment by DamienCassou** [comment]
Damien*s* and Lusy, we were 3 working hard on that
