### ISSUE TITLE
Add an introductory paragraph

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#33]
Something including

> Enterprise Pharo is the third volume of the series. This book covers libraries and frameworks for enterprises, and in particular those doing web development.

This should probably be in the same page as the Authors list. But the page title will have to be changed.

/cc @cdlm do you have an idea of a nice page title with both authors and introduction? Foreword? Preface?

**Comment by cdlm** [comment]
Both *foreword* and *preface* work, but what about *About this book* ?

**Comment by cdlm** [comment]
Can you check and close this if it's ok?

**Comment by jfabry** [comment]
I just committed an extended edition. Please have a look. If it's OK for both of you we can close this issue.

**Comment by DamienCassou** [comment]
Good for me. I changed a few things. Thank you both.

**Comment by cdlm** [comment]
Meh… sorry, but it's a wall of text that reveals itself to just be a condensed table of contents —which is certainly possible to do and would be visually clearer while conveying the same info. But IMHO it would be more useful to talk about *who* this book is for, and the overall quickstart/protocols/data/presentation/deployment story.

Also, writing style: why the alternance *in the Nth part* vs *part N of the book*? Just pick one, repetitions are structure.

**Comment by jfabry** [comment]
Yes I understand your point of view. The problem with the TOC is that it requires more page flipping to see the same info, plus some people do not read well TOC's. So I wanted a full text to give this kind of overview. If you have any concrete ideas feel free to change the text!

**Comment by cdlm** [comment]
I had a look and while doing a concise TOC limited to parts and chapters is possible, it requires more hacking than I have energy for :disappointed:
(see packages `shorttoc`, `tocloft`, `tocvsec2`, `minitoc`, `titletoc` and of course the docs of `memoir`)

So I'll try a short paragraph instead.
