### ISSUE TITLE
Proof-read a printed version of Zinc WebSockets chapter

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#40]

**Comment by jfabry** [comment]
See also issue #12

**Comment by DamienCassou** [comment]
Damien P. and I did some fixes on this chapter (b14f645476c1d91b80ec86ffd1ce7d9ea496ea92 and 27b420a86baedbc8fdb5ee3ed2b6b7fc57ebb669). I don't think it is necessary to look at it again but feel free to do so nonetheless.

**Comment by jfabry** [comment]
Previous fixes were good, but I wanted to check hyphenation as well. Done!
