### ISSUE TITLE
Proof-read a printed version of Deployment chapter

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#50]

**Comment by jfabry** [comment]
Working on this right now. This has never been proof-read by an editor and needs some work!

**Comment by DamienCassou** [comment]
Johan Fabry <notifications@github.com> writes:
> Working on this right now. This has never been proof-read by an editor
> and needs some work!

thanks

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jfabry** [comment]
Previous commit addresses this issue, but additionally includes a short conclusions section that ends the book cleanly. Without it the ending of the book was indeed too abrupt. Maybe @DamienCassou you want to double check this, so I'm leaving this issue open for you to decide.

**Comment by DamienCassou** [comment]
working on it
