### ISSUE TITLE
Circular Pillar documentation links

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/EnterprisePharo#53]
The README says "If you are not familiar with it please check the https://github.com/pillar-markup/pillar-documentation".

But https://github.com/pillar-markup/pillar-documentation refers you back to the Pillar chapter on this repo.

The README paragraph should be changed to:
"If you are not familiar with it please see the Pillar chapter".

**Comment by DamienCassou** [comment]
Thanks
