### ISSUE TITLE
Pillar - document escaping characters

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/EnterprisePharo#54]
1. Document the backslash as an escape character. 
2. List the characters that need escaping (`+`, `|`,  `#`, `-`, etc).

In the `Raw` section, make sure to point out that inline verbatim code in ``== ==`` still needs to escape special characters. (This is counter-intuitive to general verbatim/monospace semantics).

**Comment by DamienCassou** [comment]
thanks
