### ISSUE TITLE
Script references don't work anymore

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#63]
This is due to new LaTeX package used for showing scripts.

**Comment by DamienCassou** [comment]
This is a bug in Pillar. https://github.com/pillar-markup/pillar/issues/98

**Comment by cdlm** [comment]
Here's where I am in [my branch of sbabook](https://github.com/cdlm/sbabook/tree/listing-environment); displayed code, not referenceable, appears in the flow of paragraphs, mandatory language (here, `[Visual]Basic`):

```
\begin{displaycode}{[Visual]Basic}
10 PRINT "Hello SBAbook!"
20 PRINT "This is a paragraph-level listing."
30 GOTO 10
\end{displaycode}
```

Referenceable code, mandatory caption after the language, optional label and float specifier:

```
\begin{listing}[float,label=lst:fooNewWith]{Smalltalk}{A factory method in class \code{Foo}}
Foo class>>with: parameter
  ^ self new
    initializeWith: parameter
\end{listing}
```

If Pillar supports short captions for the table of contents, add this key in the optional argument: `list text={blah}`

**Comment by DamienCassou** [comment]
- why is `label` optional? What's the point of an unreferenceable floating script?

**Comment by cdlm** [comment]
It's just technically possible, and if `float` is omitted then it will just be like a `displaycode` but with a caption —not sure that fully makes sense, now that I write it like that; I can change it.

Technically it's the same for the caption, but I made it mandatory because it's the main visible difference, and leaving it empty would make an anonymous entry in the table of illustrations.

**Comment by DamienCassou** [comment]
do you have a new proposal considering the usefulness of `float` and optional `label`?

**Comment by DamienCassou** [comment]
ok, we discussed IRL and decided:

- if a script has both no label and no caption, it should be a `displaycode`, otherwise, it is a `listing`
- if a script has no label, we don't care and generate no `label=...`
- if a script has no caption, we generate an empty caption and raise a warning
- if a script has no language, we generate `plain`
- it should be possible to specify a `shortcaption` in Pillar to get a `list text={...}`

**Comment by DamienCassou** [comment]
looking at Enterprise Pharo, I found:

- 10 scripts with a caption
- 5 scripts with a label
- 5 scripts with both a label and a caption

**Comment by DamienCassou** [comment]
I've made required changes in Pillar sources code. Now, I have the impression that `\code{}` has been defined in https://github.com/cdlm/sbabook/tree/listing-environment and this breaks my build.
