### ISSUE TITLE
Chapter PDFs have no index

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#70]
Look at the left pane of this screenshot:
![no-index-in-pdf](https://cloud.githubusercontent.com/assets/217543/13819766/f67e3bbe-eb9a-11e5-96ed-06257d983b7e.png)

We should normally see a list of sections and subsections of this chapter. We only see the chapter title.

**Comment by DamienCassou** [comment]
reported upstream: https://github.com/cdlm/sbabook/issues/7

**Comment by DamienCassou** [comment]
Thanks @cdlm. I've updated the Voyage chapter to remove code in headers (but this has no impact because those where subsubsections and not in the index).

**Comment by cdlm** [comment]
I specifically set the bookmarks level to stop at subsections because of this. Since they fold/unfold in the PDF reader I thought we could make them deeper than the paper table of contents.

**Comment by DamienCassou** [comment]
Damien Pollet <notifications@github.com> writes:

> I specifically set the bookmarks level to stop at subsections because
> of this. Since they fold/unfold in the PDF reader I thought we could
> make them deeper than the paper table of contents.

agree. You can change it now if you like. Thanks Damien.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by cdlm** [comment]
Done in 1123abc
