### ISSUE TITLE
Captions and labels in listings are mixed

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#74]
Both the [sbabook documentation](https://github.com/cdlm/sbabook/blob/0024b02f2f6910e098b5f225680f09e6a9ebb423/sbabook.tex#L294) and [old issue](https://github.com/SquareBracketAssociates/EnterprisePharo/issues/63) say that listings have 2 mandatory arguments, the caption being the second one:

```latex
\begin{listing}[float]{ston}{Export into a specific folder}
{
  "title" : "My first document while reading the 5 minutes Pillar tutorial",
  "outputDirectory" : "result"
}
\end{listing}
```

but, this does not work. I have the impression that this environment expects a third mandatory argument for the label. With no 3rd argument, the listing content is used as the caption, and `Export into a specific folder` is used as a label. Indeed, in [an sbabook example](https://github.com/cdlm/sbabook/blob/0024b02f2f6910e098b5f225680f09e6a9ebb423/sbabook.tex#L303), this is how listings are used:

```latex
\begin{listing}{Smalltalk}{lst:fooNewWith}
{A factory method in class \code{Foo}}
Foo class>>with: parameter
  ^ self new
    initializeWith: parameter
\end{listing}
```

What should I do?

**Comment by cdlm** [comment]
Use the source, Luke :) Documentation is by definition out of date…

**Comment by DamienCassou** [comment]
what should pillar output when the author provides a caption and no label? Previously you said that was fine.
