### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#75]
I propose we capitalize all words of section titles except simple ones (the, of, a, ...).

What do you think?

**Comment by LucFabresse** [comment]
+1

**Comment by Ducasse** [comment]
ok for me

**Comment by Ducasse** [comment]
but not paragraph

**Comment by DamienCassou** [comment]
@Ducasse what do you means by

> but not paragraph

?

**Comment by Ducasse** [comment]
you do not want to have paragraph label capitalised

> On 18 Mar 2016, at 11:31, Damien Cassou <notifications@github.com> wrote:
> 
> @Ducasse <https://github.com/Ducasse> what do you means by
> 
> but not paragraph
> 
> ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/SquareBracketAssociates/EnterprisePharo/issues/75#issuecomment-198298053>

--------------------------------------------
Stéphane Ducasse
http://stephane.ducasse.free.fr
http://www.synectique.eu / http://www.pharo.org 
03 59 35 87 52
Assistant: Julie Jonas 
03 59 57 78 50
03 59 35 86 16

S. Ducasse - Inria
40, avenue Halley, 
Parc Scientifique de la Haute Borne, Bât.A, Park Plaza
Villeneuve d'Ascq 59650
France

**Comment by jfabry** [comment]
+1

**Comment by DamienCassou** [comment]
Done
