### ISSUE TITLE
Replace Class >> method by Class>>method everywhere

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#78]
/cc @cdlm @Ducasse is that ok?

**Comment by cdlm** [comment]
For method declarations and qualifying method selectors, yes. But keep the
spaces if it's meant as the >> operator somewhere in code.

On 22 March 2016 at 13:09, Damien Cassou <notifications@github.com> wrote:

> /cc @cdlm <https://github.com/cdlm> @Ducasse <https://github.com/Ducasse>
> is that ok?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SquareBracketAssociates/EnterprisePharo/issues/78>
>



-- 
Damien Pollet
type less, do more [ | ] http://people.untyped.org/damien.pollet
