### ISSUE TITLE
NeoJSON and NeoCSV chapters have incoherent titles

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#83]
- JSON
- Handling CSV with NeoCSV

How should we rename the chapters to get some coherence? Because the library names are clear enough, I propose

- NeoJSON
- NeoCSV

/cc @jfabry @LucFabresse @svenvc @Ducasse

**Comment by jfabry** [comment]
I'm OK with your suggestion.

**Comment by LucFabresse** [comment]
yes


#Luc

2016-04-19 17:46 GMT+02:00 Johan Fabry <notifications@github.com>:
