### ISSUE TITLE
Add Lusy acknowledgment

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#86]
I propose we acknowledge the work of Lusy in the same page where we list authors.

**Comment by cdlm** [comment]
👍
…or with the sbabook mention in the colophon, as that's usually where cover design credits go.

**Comment by DamienCassou** [comment]
Can we close this one?

**Comment by cdlm** [comment]
If she's ok with how it is now, sure

**Comment by DamienCassou** [comment]
no, we should write `Liudmyla Dolia` instead.

**Comment by cdlm** [comment]
Updated in the TeX files, I'll leave the cover graphics to you

**Comment by DamienCassou** [comment]
I keep that open until I reupload the cover to lulu. Thanks Damien.

**Comment by DamienCassou** [comment]
done
