### ISSUE TITLE
Fuel's homepage must be updated

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#90]
In section "Some links" of the Fuel's chapter, check Fuel's homepage link

**Comment by tinchodias** [comment]
I can take a look in a couple of hours.

**Comment by tinchodias** [comment]
I don't see anything wrong with homepage except it had no news for a long
long time. The only thing I found is to update the url of the Issue Tracker
which has been moved from google.code.

**Comment by tinchodias** [comment]
Damien, is there something else that must be updated? I didn't understand
the issue.

**Comment by DamienCassou** [comment]
I meant 29b9e37, thanks
