### ISSUE TITLE
Code blocks in the Pillar chapter do not have the margin bar

### ISSUE THREAD

**Issue by cdlm** [SquareBracketAssociates/EnterprisePharo#95]
But what Pillar produces has the bar… it should be the other way around, if you think of the bar as indicating code, and no bar like a sort of figure

**Comment by DamienCassou** [comment]
In the image, I should change `PRSBALaTeXWriter>>visitPreformatted:` to use `displaycode` instead of `verbatim`

**Comment by DamienCassou** [comment]
done with Pillar v3.0.3.
