### ISSUE TITLE
Get ISBN and barcode

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#99]

**Comment by DamienCassou** [comment]
I've just sent an email to Oscar

**Comment by DamienCassou** [comment]
@onierstrasz and @Ducasse recommand asking Lulu for the ISBN. I did:

```
978-1-326-65097-1
```

I also added [`cover/isbn_barcode.pdf`](https://github.com/SquareBracketAssociates/EnterprisePharo/blob/master/cover/isbn_barcode.pdf) to the repository.

The barcode width must be 4,65 cm (1.833") and its height must be 2,54 cm (1").

**Comment by DamienCassou** [comment]
@cdlm could you please adapt the cover with the ISBN while you modify it? Else I will do it.

**Comment by cdlm** [comment]
Committed; I didn't check the precise dimensions (Inkscape's UI is crap for controlling which image is at which DPI…)
